apiVersion: v1
kind: Service
metadata:
    name: backend-service
    labels:
        run: backend-service
spec:
    selector:
      app: feed-backend
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
