apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: frontend
          image: whadiyatalkinabeet/feed:frontend
          ports:
          - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
      - name: myregistrykey
